#When A Player Die Send Dead Location For Them.
DeathMessage:
  toggle: true

#When A Player Die Log Their Location, World, Date In TxT File.
NickName:
  toggle: true

#When A Player Joining The Server Check Their Rank If They Have It Skip And If Not Reset Their Name Into The Default.
PlayerDeathLogger:
  toggle: true

#For /Back Command In FFA Crystal On PracticePvP.
PracticeBackCommand:
  enable: true

