name: LDCore
version: '${project.version}'
main: me.litedeforged.ldcore.LDCore
api-version: '1.19'
depend:
  - Essentials
  - StrikePractice
commands:
  back:
    permission: 'ldcore.practicepvp.commands.back'