name: LDCore
version: '${project.version}'
main: me.litedeforged.ldcore.LDCore
api-version: '1.19'
depend:
  - Essentials
  - StrikePractice
  - ajParkour
commands:
  lastdeathlocation:
    permission: 'ldcore.practicepvp.commands.lastdeathlocation'
  changerollbackspeed:
    permission: 'ldcore.practicepvp.commands.changerollbackspeed'
  partylimit:
    permission: 'ldcore.practicepvp.commands.partylimit'
  forcearenarollback:
    permission: 'ldcore.practicepvp.commands.forcearenarollback'
  clientdetector:
    permission: 'ldcore.game.commands.clientdetector'
  ff:
    permission: 'ldcore.game.commands.ff'